name: Josh Dawson
favicon: null
layout_spectrum: 0.37371115991845727
typography_spectrum: 0.7479313316289335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7371367753949016
  lightness: 0.22502700192853808
  saturation: 0.8117844159714878
  rhythmicContrast: 0.39317078329622746
purpose: []
